"""
predict.py

The single prediction pipeline used by BOTH the CLI (`python src/predict.py
image.jpg`) and the Flask app (via app/services/model_service.py). This
guarantees the web app's predictions are produced by exactly the same code
path that was evaluated in evaluate.py.

Class names are loaded from models/class_names.json (generated by
src/split_dataset.py) - never hard-coded here.

Returns either:
    {"status": "success", "plant": ..., "disease": ..., "confidence": ...}
or:
    {"status": "uncertain", "message": "..."}
or:
    {"status": "error", "message": "..."}
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any, Dict

import numpy as np

from src.config_loader import load_config, resolve_path, get_image_size
from src.preprocessing import load_and_preprocess_image, batch_to_tensor, InvalidImageError

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

_model = None  # module-level cache so the model is loaded only once per process
_class_names: list[str] | None = None


def _split_plant_and_disease(class_name: str) -> tuple[str, str]:
    """
    PlantVillage-style class names look like 'Tomato___Early_blight'.
    Falls back gracefully if the dataset uses a different naming scheme.
    """
    if "___" in class_name:
        plant, disease = class_name.split("___", 1)
    elif "__" in class_name:
        plant, disease = class_name.split("__", 1)
    else:
        plant, disease = class_name, class_name
    return plant.replace("_", " "), disease.replace("_", " ")


def load_model_and_classes(model_path: Path | None = None):
    """Loads the model and class names once, caching them at module level.

    Checks for the required files BEFORE importing TensorFlow, so that on
    a fresh clone (no dataset/model trained yet) this fails fast with a
    clear FileNotFoundError rather than requiring TensorFlow to even be
    installed just to discover that no model exists.
    """
    global _model, _class_names

    cfg = load_config()
    if _class_names is None:
        class_names_path = resolve_path(cfg["paths"]["class_names_file"])
        if not class_names_path.exists():
            raise FileNotFoundError(
                f"{class_names_path} not found. Train a model first (this file is "
                "generated by src/split_dataset.py)."
            )
        with open(class_names_path, "r", encoding="utf-8") as f:
            _class_names = json.load(f)

    if _model is None:
        path = model_path or resolve_path(cfg["paths"]["best_model_path"])
        if not path.exists():
            raise FileNotFoundError(
                f"No trained model found at {path}. See README for training instructions."
            )
        import tensorflow as tf  # imported lazily, only once a model actually needs loading

        logger.info("Loading model from %s ...", path)
        _model = tf.keras.models.load_model(path)
        logger.info("Model loaded.")

    return _model, _class_names


def predict_image(image_path_or_file, model_path: Path | None = None) -> Dict[str, Any]:
    """Run the full prediction pipeline on a single image."""
    cfg = load_config()
    threshold = cfg["inference"]["confidence_threshold"]

    try:
        model, class_names = load_model_and_classes(model_path)
    except FileNotFoundError as exc:
        return {"status": "error", "message": str(exc)}

    try:
        arr = load_and_preprocess_image(image_path_or_file, get_image_size())
    except InvalidImageError as exc:
        return {"status": "error", "message": f"Invalid image: {exc}"}

    tensor = batch_to_tensor(arr)
    probs = model.predict(tensor, verbose=0)[0]
    top_idx = int(np.argmax(probs))
    confidence = float(probs[top_idx])
    class_name = class_names[top_idx]
    plant, disease = _split_plant_and_disease(class_name)

    if confidence < threshold:
        return {
            "status": "uncertain",
            "message": (
                "Unable to confidently identify this leaf. "
                "Please upload a clear, well-lit, close-up image of a single plant leaf."
            ),
            "raw_top_guess": class_name,
            "confidence": confidence,
        }

    return {
        "status": "success",
        "class_name": class_name,
        "plant": plant,
        "disease": disease,
        "confidence": confidence,
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run a single prediction from the CLI.")
    parser.add_argument("image_path", type=str, help="Path to a leaf image")
    parser.add_argument("--model", type=str, default=None)
    args = parser.parse_args()

    model_path = resolve_path(args.model) if args.model else None
    result = predict_image(args.image_path, model_path=model_path)
    print(json.dumps(result, indent=2))
